### ISSUE TITLE
About bandwidth

### ISSUE THREAD

**Issue by hardx-011** [lvwj19/PPR-Net-plus#10]
Hi, thanks for your excellent work!

According to your paper and code, I wonder if the bandwidth in the code is calculated according to the map function in the paper? (In the evaluate code, 'MeanShift(bandwidth=10)')
And how to get object's compactness r80%? Is there any code to compute?

Look forward to your reply!

**Comment by lvwj19** [comment]
Thanks for your attention! In the paper, we use the mapping function to demonstrate the correlation between the compactness of the predicted centroid cluster and the optimal bandwidth. The compactness of the predicted centroid cluster is also related to the training performance of the network. Generally, the better network model predicts the centroid clusters with better compactness. 

As for the calculation of compactness, our method is to find the predicted centroid cluster belonging to an individual according to the point-wise individual label, then calculate the center point, and take the distance of the 80% closest point to the center point (r80%) as the compactness measurement of the predicted centroid cluster, i,e., the larger r80% means the smaller compactness. The above process is easy for numpy to calculate and analyze.

In the actual application process, we recommend using the visualization performance to select the appropriate bandwidth for a quick application test. For example, in the evaluate code, 'MeanShift(bandwidth=10)'  was set by the the visualization performance, which was basically suitable for our trained model. 
For AP evaluation and comparison, it is recommended to use the mapping function for optimal bandwidth selection. At the same time, the highest AP has a trade-off between precision and recall,  so the corresponding optimal bandwidth may not suitable for some actual applications which may have a preference for precision or recall.

**Comment by hardx-011** [comment]
I see! Thanks for your detailed reply！！
