### ISSUE TITLE
Would you like to share the parameters for other objects?

### ISSUE THREAD

**Issue by 4-0-4-notfound** [lvwj19/PPR-Net-plus#13]
Hello, i want to know the difference of parameters between difference object.

What is the key parameter between difference objects?  (Num. of layer?  npoints per layer? radius per layer? or other parameters?)

Would you like to share the parameters for other objects, like T-Less, Gear, Brick etc.

**Comment by Windson9** [comment]
@4-0-4-notfound Were you able to train with any custom dataset of yours?
