### ISSUE TITLE
picked_idx = pred_conf_val[:,1] > 0.5

### ISSUE THREAD

**Issue by BharathRajM** [lvwj19/PPR-Net-plus#17]
The confidence values are in negatives(-1.5,-1.76~~~~~), even while evaluating your trained model.
Could you recheck this in line #128 of the evaluate.py?

**Comment by lyl1140292193** [comment]
I encountered the same problem.While evaluating the h5 files in h5_dataset/bunny/cycle_0000.zip with the given trained model,the detected confidence values are all near to zero.Anyway,the selected data with threshold 0.5 is none.

**Comment by lyl1140292193** [comment]
I encountered the same problem.While evaluating the h5 files in h5_dataset/bunny/cycle_0000.zip with the given trained model,the detected confidence values are all near to zero.Anyway,the selected data with threshold 0.5 is none.

**Comment by lvwj19** [comment]
Thanks for your attention! We have fixed this problem，and you can try it again.

without confidence filter
![9c6b906b8acc3c6594a2c6233f245446_](https://github.com/lvwj19/PPR-Net-plus/assets/48743308/9e87e8cf-dea5-4820-8d45-3d7a9038a01b)

with confidence filter
![3d63d63e18b179a0b003bc49b58536aa_](https://github.com/lvwj19/PPR-Net-plus/assets/48743308/1ed8c1d4-c0c2-4322-b923-74f617d9e149)
