### ISSUE TITLE
Encountered some errors while using

### ISSUE THREAD

**Issue by nuo-code** [lvwj19/PPR-Net-plus#2]
Hello、When I use the library, I get the following error：ImportError: /home/nuo/PycharmProjects/PPR-Net-plus/pprnet/backbone/pointnet2/_ext.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs.I don't know how to solve this problem, can you provide some help？

**Comment by lvwj19** [comment]
You can compile the CUDA layers for PointNet++ to generate .so for your own environment:

cd pointnet2
python setup.py install

**Comment by nuo-code** [comment]
Thank you
