### ISSUE TITLE
special objects

### ISSUE THREAD

**Issue by trungpham2606** [lvwj19/PPR-Net-plus#3]
Hi @lvwj19 
According to your paper, I have a question that can the model work well in case of symmetric objects like cube or rectangular prism ? (where the pose will be defined according to the top and bottom of the object, same shape but different color or texture).

**Comment by lvwj19** [comment]
If there is a colored point cloud, you can define G as an identity matrix  and the object will be treated as asymmetric. If the point cloud has no color and the shape is symmetrical, define G as a symmetrical treatment.

**Comment by trungpham2606** [comment]
@lvwj19 
If i want to use pprnetplus, what should it be the value of conf_head in loss_weights ?

**Comment by lvwj19** [comment]
loss_weights = {
    'trans_head': 200.0/1000.0, # implicit convert mm to m by deviding 1000
    'rot_head': 200.0,
    'vis_head': 50.0,
    'conf_head': 10.0
}

**Comment by trungpham2606** [comment]
@lvwj19 
How can I define the G identity matrix for color point cloud ?
