### ISSUE TITLE
Train dataset

### ISSUE THREAD

**Issue by Junyu-Zhu** [lvwj19/PPR-Net-plus#4]
Hi, I've tried to generate train dataset in the file convert_to_pointcloud/bunny/generate_train_dataset.py. But it shows me the error about tensorflow like following picture
![libcudart](https://user-images.githubusercontent.com/87128891/145182182-cde07ff0-8e9b-4ec1-a7bb-aff30095dbcf.png)
I used tensorflow2.4.0, cuda11.0. Can you tell me what's the exact version of tensorflow and cuda when you generated the train dataset. And is this generated dataset the same as the dataset when you trained the pprplus net? Thanks a lot.

**Comment by lvwj19** [comment]
The code can run in tensorflow1.5.0, cuda9.0.
The dataset generation process for pprnet++ is the same as pprnet.

**Comment by Junyu-Zhu** [comment]
Ok,  thanks a lot.
