### ISSUE TITLE
Pretrain model for testing

### ISSUE THREAD

**Issue by rcao-hk** [lvwj19/PPR-Net-plus#5]
Hello, 

Thank you for your excellent work!
Could you provide pre-trained models for Sileane and IPA datasets?

Best,
Rui

**Comment by lvwj19** [comment]
We have provided a pretrained model (but not the same as the models in our papers, which were trained in tensorflow) for bunny object of IPA datasets in PPR-Net-plus/h5_dataset/bunny/bunny_pprplus.tar. As for other objects of Sileane and IPA datasets, you can train the models by yourself.

**Comment by rcao-hk** [comment]
Hi,
Thank you for your reply.
Could you provide the pprnet and pprnet++'s pose estimation results for the Sileane dataset and IPA real datasets ( Ring Screw and Gear Shaft) for evaluation and comparison?
Thank you.

Best,
Rui

**Comment by lvwj19** [comment]
You can find the pose estimation results in PPR-Net++: Accurate 6D Pose Estimation in Stacked Scenarios.
