### ISSUE TITLE
how to get different obj models for calculating lambda 

### ISSUE THREAD

**Issue by Junyu-Zhu** [lvwj19/PPR-Net-plus#6]
First, thank you for this excellent work. 
And now I'm trying the codes of evaluating with the real-wrold data RingScrew models. But at /models, there is only obj models of bunny. And I tried to transfer RingScrew stl CAD models from the Fraunhofer IPA Bin-Picking dataset to obj models. But it shows me errors like "ValueError: could not convert string to float: '1//1'" when running the calc_lambda.py. 
So, I have questions about how to get the right RingScrew obj models, is my way that transfer IPA dataset stl CAD models to obj correct? Or how can I export different obj models like the bunny which you already provide? Thanks a lot.

**Comment by lvwj19** [comment]
Thanks for your attention. We have used the software "MeshLab" to convert the stl  model to obj model, and it's free to download. Use "MeshLab" to load stl model, and save as obj model.

**Comment by Junyu-Zhu** [comment]
It works, thanks a lot
