### ISSUE TITLE
Settings about camera intrinsic parameters

### ISSUE THREAD

**Issue by xumingkun9806** [lvwj19/PPR-Net-plus#9]
The data set generated in the virtual environment, is it better to set the camera internal parameters to coincide with your real camera?  
For example, the cu and cv parameters of the real camera are not half the resolution, so I'm in a virtual data set the same parameters as the real camera.But it didn't work out well, what do you think?
Look forward to your reply

**Comment by lvwj19** [comment]
Thanks for your attention. It is better to set the camera internal parameters to coincide with your real camera. I suggest that you observe the characteristics of the real data, and then make the simulated data more realistic, such as adding noise, normalizing the data range, or adding some holes at the edges, mainly to see if the real data is too different from the simulated data.

**Comment by xumingkun9806** [comment]
Thanks a lot,thanks for your advice.My problem is my real camera internal parameters is    fx=1740.1576313571834,fy=1740.1718443908405,cx=636.8015498880756,cy=487.72275875956717
so I set the internal parameters of virtual camera the same as fx=1740.1576313571834,fy=1740.1718443908405,cx=636.8015498880756,cy=487.72275875956717，
but When I'm testing in a simulated scenario，it didn't work out well. Beacause I set too precise?
And  you say “I suggest that you observe the characteristics of the real data” ，What does it mean？
Thank you！

**Comment by lvwj19** [comment]
Sorry, I misunderstood what you meant, and the suggestion is for the trained model which is good for simulated data but bad in real data.

I don't think that the settings are too precise. Our camera parameters are fx=2730,fy=2730,cx=960,cy=600. Maybe there is something wrong with your camera model? You can check if your point cloud data and pose labels are consistent.

**Comment by xumingkun9806** [comment]
Thank you！But I want to know why you don‘t set the  virtual camera parameters as your  real calibration camrea( have distortion）.

**Comment by lvwj19** [comment]
In our experiments, the settings of the virtual camera and the real camera are the same.

**Comment by xumingkun9806** [comment]
so your real camrea settings is  fx=2730,fy=2730,cx=960,cy=600？

**Comment by lvwj19** [comment]
Yes, it is the setting of Mech-Eye camera.

**Comment by xumingkun9806** [comment]
I use this camrea now,through mech-viz calibration.I get fx=2734.497171257693,fy=2734.2139842813203,cx=966.7210274621965,cy=626.0787916680408,I need to set the virtual settings is this or  fx=2730,fy=2730,cx=96
0,cy=600?And Mech camrea use structured light，and I get 
![屏幕截图 2022-04-26 115640](https://user-images.githubusercontent.com/61106108/165217983-6c19ce0d-7661-4dd6-ad14-f657b2dd372f.png)
tent.com/61106108/165217648-1ebc4fd3-c53c-431a-be8f-45e59a45469e.png)
so you think the stripe in surface will  influence the net preformence

**Comment by lvwj19** [comment]
The parameter settings that we set, are fx=2730,fy=2730,cx=960,cy=600,  but you can set it more accurately, like fx=2734.497171257693,fy=2734.2139842813203,cx=966.7210274621965,cy=626.0787916680408. 

I don't think that the stripes in surface influence the network preformence.

**Comment by xumingkun9806** [comment]
ok，thans a lot.
